spring.application.name=grocery-db

spring.datasource.url=jdbc:mysql://localhost:3306/grocery_db
spring.datasource.username=root
spring.datasource.password=moom13.07

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true